# Generated by Django 5.1.7 on 2025-03-31 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='assigned_taxi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.taxi'),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='model',
            field=models.CharField(default='Toyota Prius', max_length=50),
        ),
    ]
