# Generated by Django 5.1.7 on 2025-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_driver_assigned_taxi_alter_taxi_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='route',
            field=models.JSONField(default=list),
        ),
    ]
