# Generated by Django 5.1.7 on 2025-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_taxi_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='route',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
