# Generated by Django 5.1.7 on 2025-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_anomaly_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='current_ride_name',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
