# Generated by Django 5.1.7 on 2025-04-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_taxi_current_lat_alter_taxi_current_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='ride_name',
            field=models.CharField(default='unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='current_ride_name',
            field=models.CharField(default='unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
