# Generated by Django 5.1.7 on 2025-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_anomaly_ride_name_alter_taxi_current_ride_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='lat',
            field=models.FloatField(default=43.239819),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='long',
            field=models.FloatField(default=76.903932),
        ),
    ]
