# Generated by Django 5.1.7 on 2025-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_anomaly_lat_anomaly_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='taxi',
            name='current_metrics',
            field=models.JSONField(default=dict),
        ),
    ]
