# Generated by Django 5.1.7 on 2025-04-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_anomaly_metrics_taxi_current_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
