# Generated by Django 5.1.7 on 2025-04-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_driver_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('ride_name', models.CharField(default='unknown', max_length=300)),
                ('lat', models.FloatField(default=43.239819)),
                ('long', models.FloatField(default=76.903932)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.driver')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.taxi')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('ride_name', models.CharField(default='unknown', max_length=300)),
                ('lat', models.FloatField(default=43.239819)),
                ('long', models.FloatField(default=76.903932)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.driver')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.taxi')),
            ],
        ),
    ]
