# Generated by Django 5.1.7 on 2025-04-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_dailyanomaly_weeklyanomaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyanomaly',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weeklyanomaly',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
