# Generated by Django 5.1.7 on 2025-04-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_alter_dailyanomaly_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(default='unknown', max_length=300)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0)),
                ('duration', models.FloatField(default=0.0)),
                ('start_finish_lat_lon', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(default=0.0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.driver')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.taxi')),
            ],
        ),
        migrations.AddField(
            model_name='anomaly',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='tracking.trip'),
        ),
    ]
