# Generated by Django 5.1.7 on 2025-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_trip_anomaly_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyanomaly',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weeklyanomaly',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
