# Generated by Django 5.1.7 on 2025-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_alter_dailyanomaly_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='on_trip_status',
            field=models.CharField(default='not on trip', max_length=50),
        ),
    ]
