# Generated by Django 5.1.7 on 2025-04-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_driver_new_taxi_lat_driver_new_taxi_lon_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.customer'),
        ),
    ]
