# Generated by Django 5.1.7 on 2025-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_remove_anomaly_trip_trip_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='passenger_in_danger',
            field=models.BooleanField(default=False),
        ),
    ]
