# Generated by Django 5.1.7 on 2025-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_taxi_passenger_in_danger'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profil_picture',
            field=models.ImageField(blank=True, default='profile_pictures/profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
