# Generated by Django 5.1.7 on 2025-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_driver_profil_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profil_picture',
            field=models.ImageField(blank=True, default='static/profile_pictures/profile.png', null=True, upload_to='static/profile_pictures/'),
        ),
    ]
