# Generated by Django 5.1.7 on 2025-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_endangeredpassengercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='heading',
            field=models.FloatField(default=0.0),
        ),
    ]
