# Generated by Django 5.1.7 on 2025-04-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='current_passenger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.customer'),
        ),
    ]
